apiVersion: v1
kind: Secret
metadata:
  name: wp-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: somewordpress
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress
  MYSQL_PASSWORD: wordpress
